//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_RECETAS.Domain.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Recetas
    {
        public int RecetaId { get; set; }
        public string CodigoUnico { get; set; }
        public int PacienteId { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public int EstadoId { get; set; }

    
        public virtual EstadosReceta EstadosReceta { get; set; }
    }
}
